# Generated by Django 4.2.3 on 2023-08-24 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('library', '0001_initial'),
        ('academy', '0002_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=20, null=True, unique=True, verbose_name='원번')),
                ('ar_correct', models.IntegerField(blank=True, null=True)),
                ('ar_date', models.DateField(blank=True, null=True, verbose_name='ar 퀴즈푼 날짜')),
                ('lit_correct', models.IntegerField(blank=True, null=True)),
                ('lit_date', models.DateField(blank=True, null=True, verbose_name='lit 퀴즈푼 날짜')),
                ('month', models.IntegerField(blank=True, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_records', to='library.book', verbose_name='읽은 도서')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_records', to='user.student', verbose_name='학생')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_time', models.DateTimeField(blank=True, null=True, verbose_name='입장시간')),
                ('exit_time', models.DateTimeField(blank=True, null=True, verbose_name='퇴장시간')),
                ('status', models.CharField(choices=[('attendance', '등원'), ('completed', '하원'), ('cancelled', '취소'), ('late', '지각'), ('absent', '결석'), ('makeup', '결석 (보강)')], default=None, max_length=10, null=True, verbose_name='상태')),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='academy.lecture', verbose_name='강의')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='user.student', verbose_name='학생')),
            ],
        ),
    ]
