# Generated by Django 4.2.3 on 2023-09-26 04:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('student', '0002_attendance_memo'),
    ]

    operations = [
        migrations.CreateModel(
            name='SummaryReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=20, verbose_name='원번')),
                ('recent_study_date', models.DateField(blank=True, null=True, verbose_name='최근 학습 일')),
                ('this_month_ar', models.FloatField(blank=True, null=True)),
                ('last_month_ar', models.FloatField(blank=True, null=True)),
                ('ar_diff', models.FloatField(blank=True, null=True)),
                ('this_month_wc', models.IntegerField(blank=True, null=True)),
                ('last_month_wc', models.IntegerField(blank=True, null=True)),
                ('total_wc', models.IntegerField(blank=True, null=True)),
                ('this_month_correct', models.IntegerField(blank=True, null=True)),
                ('last_month_correct', models.IntegerField(blank=True, null=True)),
                ('total_correct', models.IntegerField(blank=True, null=True)),
                ('this_month_bc', models.IntegerField(blank=True, null=True)),
                ('last_month_bc', models.IntegerField(blank=True, null=True)),
                ('total_bc', models.IntegerField(blank=True, null=True)),
                ('this_month_study_days', models.IntegerField(blank=True, null=True)),
                ('last_month_study_days', models.IntegerField(blank=True, null=True)),
                ('total_study_days', models.IntegerField(blank=True, null=True)),
                ('update_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summary_report', to='user.student', verbose_name='학생')),
            ],
        ),
        migrations.CreateModel(
            name='MonthReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=20, verbose_name='원번')),
                ('month', models.IntegerField(blank=True, null=True)),
                ('bc', models.IntegerField(blank=True, null=True)),
                ('wc', models.CharField(max_length=45, null=True, verbose_name='wc')),
                ('ar', models.CharField(max_length=45, null=True, verbose_name='ar')),
                ('wc_per_book', models.CharField(max_length=45, null=True, verbose_name='wc_per_book')),
                ('correct', models.CharField(max_length=45, null=True, verbose_name='correct')),
                ('update_time', models.CharField(max_length=45, verbose_name='update_time')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='month_report', to='user.student', verbose_name='학생')),
            ],
        ),
    ]
