# Generated by Django 4.2.3 on 2023-08-14 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_alter_attendance_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('attendance', '등원'), ('completed', '하원'), ('cancelled', '취소'), ('late', '지각'), ('absent', '결석'), ('makeup', '결석 (보강)')], default='absent', max_length=10, verbose_name='상태'),
        ),
    ]
