# Generated by Django 4.2.3 on 2023-09-26 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_summaryreport_monthreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthreport',
            name='ar',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monthreport',
            name='correct',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monthreport',
            name='wc',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monthreport',
            name='wc_per_book',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
