# Generated by Django 4.2.3 on 2023-08-14 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('library', '0001_initial'),
        ('user', '0012_user_is_active'),
        ('student', '0004_alter_attendance_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_records', to='library.book', verbose_name='읽은 도서')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_records', to='user.student', verbose_name='학생')),
            ],
        ),
    ]
