# Generated by Django 4.2.3 on 2023-09-27 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_alter_attendance_lecture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='memo',
        ),
    ]
