# Generated by Django 4.2.3 on 2023-08-14 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_bookrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookrecord',
            name='ar_correct',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookrecord',
            name='ar_date',
            field=models.DateField(blank=True, null=True, verbose_name='ar 퀴즈푼 날짜'),
        ),
        migrations.AddField(
            model_name='bookrecord',
            name='lit_correct',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookrecord',
            name='lit_date',
            field=models.DateField(blank=True, null=True, verbose_name='lit 퀴즈푼 날짜'),
        ),
        migrations.AddField(
            model_name='bookrecord',
            name='month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookrecord',
            name='origin',
            field=models.CharField(max_length=20, null=True, unique=True, verbose_name='원번'),
        ),
    ]
