# Generated by Django 4.2.3 on 2023-08-14 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_bookrecord_ar_correct_bookrecord_ar_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookrecord',
            name='ar_correct',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookrecord',
            name='lit_correct',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
