# Generated by Django 4.2.3 on 2023-10-05 07:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('student', '0007_attendance_memo'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendNonFiction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pkg', models.CharField(max_length=255, verbose_name='추천논픽션 패키지')),
                ('created_at', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='패키지 선정 날짜')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommended_nonfictions', to='user.student', verbose_name='학생')),
            ],
        ),
        migrations.CreateModel(
            name='RecommendFiction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pkg', models.CharField(max_length=255, verbose_name='추천픽션 패키지')),
                ('created_at', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='패키지 선정 날짜')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommended_fictions', to='user.student', verbose_name='학생')),
            ],
        ),
    ]
