# Generated by Django 4.2.3 on 2023-08-18 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_alter_bookrecord_ar_correct_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('attendance', '등원'), ('completed', '하원'), ('cancelled', '취소'), ('late', '지각'), ('absent', '결석'), ('makeup', '결석 (보강)')], default=None, max_length=10, null=True, verbose_name='상태'),
        ),
    ]
