# Generated by Django 4.2.3 on 2023-10-06 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0009_alter_lecture_lecture_memo'),
        ('user', '0001_initial'),
        ('student', '0008_recommendnonfiction_recommendfiction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='lecture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance', to='academy.lecture', verbose_name='강의'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='attendances', to='user.student', verbose_name='학생'),
        ),
    ]
