# Generated by Django 4.2.3 on 2023-10-18 07:33

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0001_initial'),
        ('student', '0011_alter_attendance_lecture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opinion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contents', models.TextField(verbose_name='종합의견')),
                ('created_at', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='종합의견 생성 날짜')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opinion_student', to='user.student', verbose_name='학생')),
                ('writer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opinion_writer', to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
        ),
    ]
