# Generated by Django 4.2.3 on 2023-10-23 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0014_summaryreport_base_date_summaryreport_last_month_sr_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summaryreport',
            name='base_date',
        ),
        migrations.RemoveField(
            model_name='summaryreport',
            name='last_month_sr',
        ),
        migrations.RemoveField(
            model_name='summaryreport',
            name='last_per_wc',
        ),
        migrations.RemoveField(
            model_name='summaryreport',
            name='sr_diff',
        ),
        migrations.RemoveField(
            model_name='summaryreport',
            name='this_month_sr',
        ),
        migrations.RemoveField(
            model_name='summaryreport',
            name='this_per_wc',
        ),
        migrations.RemoveField(
            model_name='summaryreport',
            name='wc_diff',
        ),
    ]
