# Generated by Django 4.2.3 on 2023-10-23 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0015_remove_summaryreport_base_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='summaryreport',
            name='base_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='기준 학습 일'),
        ),
        migrations.AddField(
            model_name='summaryreport',
            name='last_month_sr',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='summaryreport',
            name='last_per_wc',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='summaryreport',
            name='sr_diff',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='summaryreport',
            name='this_month_sr',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='summaryreport',
            name='this_per_wc',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='summaryreport',
            name='wc_diff',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
