# Generated by Django 4.2.3 on 2023-07-24 04:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='지점')),
            ],
        ),
        migrations.CreateModel(
            name='Academy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='학원 이름')),
                ('location', models.CharField(max_length=200, verbose_name='위치')),
                ('branch', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='academies', to='academy.branch', verbose_name='지점')),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager_academy', to=settings.AUTH_USER_MODEL, verbose_name='매니저')),
                ('students', models.ManyToManyField(related_name='student_academies', to=settings.AUTH_USER_MODEL, verbose_name='학생들')),
                ('teachers', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_academy', to=settings.AUTH_USER_MODEL, verbose_name='선생님')),
            ],
        ),
    ]
