# Generated by Django 4.2.3 on 2023-08-24 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Academy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='학원 이름')),
                ('location', models.CharField(max_length=200, verbose_name='위치')),
                ('notification_interval', models.IntegerField(default=5, verbose_name='알람 전후 시간 설정')),
                ('end_notification_custom', models.BooleanField(default=False, verbose_name='하원/등원에 커스텀')),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='지점')),
            ],
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='강좌 날짜')),
                ('repeat_day', models.CharField(choices=[(-1, 'no-repeat'), (0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], default=0, max_length=2, verbose_name='반복 요일')),
                ('start_time', models.TimeField(verbose_name='강좌 시작 시간')),
                ('end_time', models.TimeField(verbose_name='강좌 종료 시간')),
                ('lecture_info', models.TextField(verbose_name='강좌 설명')),
                ('auto_add', models.BooleanField(default=False)),
                ('academy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='academy.academy', verbose_name='학원')),
            ],
        ),
    ]
