# Generated by Django 4.2.3 on 2023-08-24 06:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='attended_lectures', to='user.student', verbose_name='강좌 수강 학생들'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taught_lectures', to='user.teacher', verbose_name='강좌 담당 선생님'),
        ),
        migrations.AddField(
            model_name='academy',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='academies', to='academy.branch', verbose_name='지점'),
        ),
        migrations.AddField(
            model_name='academy',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager_academy', to=settings.AUTH_USER_MODEL, verbose_name='매니저'),
        ),
        migrations.AddField(
            model_name='academy',
            name='students',
            field=models.ManyToManyField(related_name='student_academies', to=settings.AUTH_USER_MODEL, verbose_name='학생들'),
        ),
        migrations.AddField(
            model_name='academy',
            name='superusers',
            field=models.ManyToManyField(related_name='purple_academies', to='user.superuser', verbose_name='퍼플'),
        ),
        migrations.AddField(
            model_name='academy',
            name='teachers',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_academy', to=settings.AUTH_USER_MODEL, verbose_name='선생님'),
        ),
    ]
