# Generated by Django 4.2.3 on 2023-07-26 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_rename_is_superuser_user_is_staff'),
        ('academy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='academy',
            name='superusers',
            field=models.ManyToManyField(related_name='purple_academies', to='user.superuser', verbose_name='퍼플'),
        ),
    ]
