# Generated by Django 4.2.3 on 2023-07-26 12:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academy', '0002_academy_superusers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='강좌 날짜')),
                ('start_time', models.TimeField(verbose_name='강좌 시작 시간')),
                ('end_time', models.TimeField(verbose_name='강좌 종료 시간')),
                ('lecture_info', models.TextField(verbose_name='강좌 설명')),
                ('academy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='academy.academy', verbose_name='학원')),
                ('students', models.ManyToManyField(blank=True, related_name='attended_lectures', to=settings.AUTH_USER_MODEL, verbose_name='강좌 수강 학생들')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taught_lectures', to=settings.AUTH_USER_MODEL, verbose_name='강좌 담당 선생님')),
            ],
        ),
    ]
