# Generated by Django 4.2.3 on 2023-09-26 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LectureInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repeat_day', models.JSONField(choices=[(-1, 'no-repeat'), (0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], default=list, verbose_name='반복 요일 (JSON)')),
                ('repeat_weeks', models.IntegerField(default=1, verbose_name='반복 주기')),
                ('start_time', models.TimeField(verbose_name='강좌 시작 시간')),
                ('end_time', models.TimeField(verbose_name='강좌 종료 시간')),
                ('about', models.TextField(verbose_name='강좌 설명')),
                ('auto_add', models.BooleanField(default=False)),
                ('academy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='academy.academy', verbose_name='학원')),
            ],
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='강좌 날짜')),
                ('lecture_memo', models.TextField(verbose_name='강좌 메모', default=None)),
                ('teacher', models.ForeignKey(on_delete=models.SET_NULL, null=True, related_name='taught_lectures', to='user.Teacher', verbose_name='강좌 담당 선생님')),
                ('lecture_info', models.ForeignKey(on_delete=models.CASCADE, related_name='lectures', to='academy.LectureInfo')),
                ('students', models.ManyToManyField(blank=True, related_name='attended_lectures', to='user.Student', verbose_name='강좌 수강 학생들')),
            ],
        ),
    ]
