# Generated by Django 4.2.3 on 2023-09-26 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0003_remove_lecture_academy_remove_lecture_auto_add_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lectureinfo',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='lectureinfo',
            name='start_time',
        ),
        migrations.AddField(
            model_name='lecture',
            name='end_time',
            field=models.TimeField(default=None, verbose_name='강좌 종료 시간'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='start_time',
            field=models.TimeField(default=None, verbose_name='강좌 시작 시간'),
        ),
    ]
