# Generated by Django 4.2.3 on 2023-07-27 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0003_lecture'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='repeat_day',
            field=models.CharField(choices=[(0, 'no-repeat'), (1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], default=0, max_length=2, verbose_name='반복 요일'),
        ),
    ]
