# Generated by Django 4.2.3 on 2023-08-07 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0005_lecture_end_notification_sent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='repeat_day',
            field=models.CharField(choices=[(-1, 'no-repeat'), (0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], default=0, max_length=2, verbose_name='반복 요일'),
        ),
    ]
