# Generated by Django 4.2.3 on 2023-09-27 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0006_alter_lecture_academy_alter_lecture_lecture_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='lecture_memo',
            field=models.TextField(default=None, verbose_name='보강 강좌 메모'),
        ),
    ]
