# Generated by Django 4.2.3 on 2023-08-08 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_remark_user'),
        ('academy', '0006_alter_lecture_repeat_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='attended_lectures', to='user.student', verbose_name='강좌 수강 학생들'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taught_lectures', to='user.teacher', verbose_name='강좌 담당 선생님'),
        ),
    ]
