# Generated by Django 4.2.3 on 2023-08-08 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0007_alter_lecture_students_alter_lecture_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academy',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='academies', to='academy.branch', verbose_name='지점'),
        ),
    ]
