# Generated by Django 4.2.3 on 2023-10-04 00:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0007_alter_lecture_lecture_memo'),
    ]

    operations = [
        migrations.AddField(
            model_name='lectureinfo',
            name='created_date',
            field=models.DateField(default=datetime.date.today, verbose_name='생성된 날짜'),
        ),
    ]
