# Generated by Django 4.2.3 on 2023-08-21 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0008_alter_academy_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='academy',
            name='end_notification_custom',
            field=models.BooleanField(default=False, verbose_name='하원/등원에 커스텀'),
        ),
        migrations.AddField(
            model_name='academy',
            name='notification_interval',
            field=models.IntegerField(default=5, verbose_name='알람 전후 시간 설정'),
        ),
    ]
