# Generated by Django 4.2.3 on 2023-08-24 06:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='사용자계정')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='사용자 이메일')),
                ('password', models.CharField(max_length=128, verbose_name='비밀번호')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='UserCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='카테고리 이름')),
            ],
        ),
        migrations.CreateModel(
            name='Remark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memo', models.TextField()),
                ('academy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memo', to='academy.academy', verbose_name='학원')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memos', to=settings.AUTH_USER_MODEL, verbose_name='회원')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='user_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.usercategory', verbose_name='카테고리'),
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('kor_name', models.CharField(default='퍼플', max_length=20, verbose_name='한국이름')),
                ('eng_name', models.CharField(default='purple', max_length=20, verbose_name='영어이름')),
                ('gender', models.CharField(choices=[('M', '남성(Man)'), ('W', '여성(Woman)')], max_length=1, verbose_name='성별')),
                ('mobileno', models.CharField(max_length=20, verbose_name='연락처')),
                ('register_date', models.DateTimeField(auto_now_add=True, verbose_name='가입일')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='출생일')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='teacher', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('academy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='academy_teachers', to='academy.academy', verbose_name='채용된 학원')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Superuser',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('academies', models.ManyToManyField(related_name='superuser', to='academy.academy', verbose_name='전체 학원')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('kor_name', models.CharField(default='퍼플', max_length=20, verbose_name='한국이름')),
                ('eng_name', models.CharField(default='purple', max_length=20, verbose_name='영어이름')),
                ('gender', models.CharField(choices=[('M', '남성(Man)'), ('W', '여성(Woman)')], max_length=1, verbose_name='성별')),
                ('mobileno', models.CharField(max_length=20, verbose_name='연락처')),
                ('register_date', models.DateTimeField(auto_now_add=True, verbose_name='가입일')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='출생일')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='student', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('pmobileno', models.CharField(max_length=20, null=True, verbose_name='부모님연락처')),
                ('origin', models.CharField(max_length=20, null=True, unique=True, verbose_name='원번')),
                ('academies', models.ManyToManyField(related_name='academy_students', to='academy.academy', verbose_name='다니는학원들')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('kor_name', models.CharField(default='퍼플', max_length=20, verbose_name='한국이름')),
                ('eng_name', models.CharField(default='purple', max_length=20, verbose_name='영어이름')),
                ('gender', models.CharField(choices=[('M', '남성(Man)'), ('W', '여성(Woman)')], max_length=1, verbose_name='성별')),
                ('mobileno', models.CharField(max_length=20, verbose_name='연락처')),
                ('register_date', models.DateTimeField(auto_now_add=True, verbose_name='가입일')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='출생일')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='manager', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('academies', models.ManyToManyField(related_name='academy_manager', to='academy.academy', verbose_name='관리중인 학원들')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
