# Generated by Django 4.2.3 on 2023-07-14 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50)),
                ('user_pw', models.CharField(max_length=256)),
                ('category_id', models.IntegerField()),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
