# Generated by Django 4.2.3 on 2023-07-18 05:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='사용자 이메일')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='UserCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='카테고리 이름')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kor_name', models.CharField(default='퍼플', max_length=20, verbose_name='한국이름')),
                ('eng_name', models.CharField(default='purple', max_length=20, verbose_name='영어이름')),
                ('gender', models.CharField(choices=[('M', '남성(Man)'), ('W', '여성(Woman)')], max_length=1, verbose_name='성별')),
                ('mobileno', models.CharField(max_length=20, unique=True, verbose_name='연락처')),
                ('register_date', models.DateTimeField(auto_now_add=True, verbose_name='가입일')),
                ('birth_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='출생 연도')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'db_table': 'user_profile',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='user_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.usercategory', verbose_name='카테고리'),
        ),
    ]
