# Generated by Django 4.2.3 on 2023-07-21 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='origin',
            field=models.CharField(max_length=20, null=True, unique=True, verbose_name='원번'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pmobileno',
            field=models.CharField(max_length=20, null=True, unique=True, verbose_name='부모님연락처'),
        ),
    ]
