# Generated by Django 4.2.3 on 2023-07-24 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_manager_student_superuser_teacher_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_superuser',
            new_name='is_staff',
        ),
    ]
