# Generated by Django 4.2.3 on 2023-07-26 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0002_academy_superusers'),
        ('user', '0004_rename_is_superuser_user_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='superuser',
            name='academies',
        ),
        migrations.AddField(
            model_name='superuser',
            name='academies',
            field=models.ManyToManyField(related_name='superuser', to='academy.academy', verbose_name='전체 학원'),
        ),
    ]
