# Generated by Django 4.2.3 on 2023-08-01 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_superuser_academies_superuser_academies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manager',
            name='birth_year',
        ),
        migrations.RemoveField(
            model_name='student',
            name='birth_year',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='birth_year',
        ),
        migrations.AddField(
            model_name='manager',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='출생일'),
        ),
        migrations.AddField(
            model_name='student',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='출생일'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='출생일'),
        ),
    ]
