# Generated by Django 4.2.3 on 2023-08-14 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0008_alter_academy_branch'),
        ('user', '0009_alter_remark_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remark',
            name='academy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memo', to='academy.academy', verbose_name='학원'),
        ),
    ]
