# Generated by Django 4.2.3 on 2023-08-14 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_remark_academy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='mobileno',
            field=models.CharField(max_length=20, verbose_name='연락처'),
        ),
        migrations.AlterField(
            model_name='student',
            name='mobileno',
            field=models.CharField(max_length=20, verbose_name='연락처'),
        ),
        migrations.AlterField(
            model_name='student',
            name='pmobileno',
            field=models.CharField(max_length=20, null=True, verbose_name='부모님연락처'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='mobileno',
            field=models.CharField(max_length=20, verbose_name='연락처'),
        ),
    ]
